# set base image (host OS)
FROM python:3.9

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY ./webapp/requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local webapp directory to the working directory
COPY ./webapp/ .

# command to run on container start
CMD [ "python", "./index.py" ]

EXPOSE 8080
